export enum ActionType {
  SET_USERS = "SET_USERS",
  SET_POSTS = "SET_POSTS",
  SET_TODOS = "SET_TODOS",
  SET_COMMENTS_FOR_POST = "SET_COMMENTS_FOR_POST",
  ADD_POST_COMMENT = "ADD_POST_COMMENT",
  SET_CURRENT_USER = "SET_CURRENT_USER",
  ADD_USER = "ADD_USER",
  UPDATE_USER = "UPDATE_USER",
  TOGGLE_TODO = "TOGGLE_TODO",
  ADD_POST = "ADD_POST",
}
