export enum ActionType {
  SET_USERS = "SET_USERS",
  SET_POSTS = "SET_POSTS",
  SET_TODOS = "SET_TODOS",
  SET_COMMENT_FOR_POST = "SET_COMMENT_FOR_POST",
  SET_CURRENT_USER = "SET_CURRENT_USER",
  ADD_USER = "ADD_USER",
  UPDATE_USER = "UPDATE_USER",
  TOGGLE_TODO = "TOGGLE_TODO",
}
